index:
    path: /
    controller: App\Controller\AccueilController::index

apropos:
    path: /apropos
    controller: App\Controller\AproposController::index

faqs:
    path: /faqs
    controller: App\Controller\FaqsController::index

home:
    path: /
    controller: App\Controller\HomeController::indexAction


userAdd :
    path: /inscription
    controller: App\Controller\UserController::addUserAction

userProfile:
    path: user/profile/{id}
    controller: App\Controller\UserController::getUserAction

userUpdate:
    path: user/profile/update/{id}
    controller: App\Controller\UserController::updateUserAction

userDelete:
    path: user/profile/delete/{id}
    controller: App\Controller\UserController::deleteUserAction


serviceAdd:
    path: user/service/{id}
    controller: App\Controller\ServiceController::addServiceAction

serviceGet:
    path: /service
    controller: App\Controller\ServiceController::getServiceAction

serviceUpdate:
  path: /user/service/{id}
  controller: App\Controller\ServiceController::updateServiceAction

serviceDelete:
  path: /user/service/{id}
  controller: App\Controller\ServiceController::deleteServiceAction



commentaireAdd:
    path: /user/service
    controller: App\Controller\ServiceController::addCommentaireAction
 
commentaireGet:
    path: /user/service/{id}
    controller: App\Controller\ServiceController::getCommentaireAction
 
commentaireUpdate:
    path: /user/service/{id}
    controller: App\Controller\ServiceController::updateCommentaireAction
 
commentaireDelete:
    path: /user/service/{id}
    controller: App\Controller\ServiceController::deleteCommentaireAction



getServiceByType:
    path: /user/serviceByType/{id}
    controller: App\Controller\ServiceController::getServiceByType    
 
 


mailboxAdd:
    path: /user/mailbox
    controller: App\Controller\MailboxController::addMailboxAction
      
mailboxGet:
    path: /user/mailbox/{id}
    controller: App\Controller\MailboxController::getMailboxAction
      
mailboxUpdate:
    path: /user/mailbox/{id}
    controller: App\Controller\MailboxController::updateMailboxAction
      
mailboxDelete:
    path: /user/mailbox/{id}
    controller: App\Controller\MailboxController::deleteMailboxAction



    
contactAdd:
    path: /contact
    controller: App\Controller\ContactController::addContactAction
      
contactGet:
    path: /admin/contact/{id}
    controller: App\Controller\ContactController::getContactAction
      
contactDelete:
    path: /admin/contact/{id}
    controller: App\Controller\ContactController::deleteContactAction