index:
    path: /
    controller: App\Controller\AccueilController::index

apropos:
    path: /apropos
    controller: App\Controller\AproposController::index

faqs:
    path: /faqs
    controller: App\Controller\FaqsController::index

home:
    path: /
    controller: App\Controller\HomeController::indexAction




userAdd :
    path: /inscription
    controller: App\Controller\UserController::addUserAction

userGet:
    path: user/user/{id}
    controller: App\Controller\UserController::getUserAction

userUpdate:
    path: user/user/{id}
    controller: App\Controller\UserController::updateUserAction

userDelete:
    path: user/user/{id}
    controller: App\Controller\UserController::deleteUserAction




serviceAdd:
    path: /user/service
    controller: App\Controller\ServiceController::addServiceAction

serviceGet:
    path: /user/service/{id}
    controller: App\Controller\ServiceController::getServiceAction

serviceUpdate:
  path: /user/service/{id}
  controller: App\Controller\ServiceController::updateServiceAction

serviceDelete:
  path: /user/service/{id}
  controller: App\Controller\ServiceController::deleteServiceAction



commentaireAdd:
    path: /user/service
    controller: App\Controller\ServiceController::addCommentaireAction
 
commentaireGet:
    path: /user/service/{id}
    controller: App\Controller\ServiceController::getCommentaireAction
 
commentaireUpdate:
    path: /user/service/{id}
    controller: App\Controller\ServiceController::updateCommentaireAction
 
commentaireDelete:
    path: /user/service/{id}
    controller: App\Controller\ServiceController::deleteCommentaireAction



getServiceByType:
    path: /user/serviceByType/{id}
    controller: App\Controller\ServiceController::getServiceByType    
 
 

mailbox:
    path: /user/mailbox
    controller: App\Controller\MailboxController::index

mailboxAdd:
    path: /user/mailbox/add
    controller: App\Controller\MailboxController::addMailbox
      
mailboxView:
    path: /user/mailbox/view/{id}
    controller: App\Controller\MailboxController::viewMailbox
      
mailboxUpdate:
    path: /user/mailbox/update/{id}
    controller: App\Controller\MailboxController::updateMailbox
      
mailboxDelete:
    path: /user/mailbox/delete/{id}
    controller: App\Controller\MailboxController::deleteMailbox



    
contactAdd:
    path: /contact
    controller: App\Controller\ContactController::addContactAction
      
contactGet:
    path: /admin/contact/{id}
    controller: App\Controller\ContactController::getContactAction
      
contactDelete:
    path: /admin/contact/{id}
    controller: App\Controller\ContactController::deleteContactAction