index:
    path: /
    controller: App\Controller\AccueilController::index

apropos:
    path: /apropos
    controller: App\Controller\AproposController::index

faqs:
    path: /faqs
    controller: App\Controller\FaqsController::index

home:
    path: /
    controller: App\Controller\HomeController::indexAction


userAdd :
    path: /inscription
    controller: App\Controller\UserController::addUserAction

userProfile:
    path: user/profile/{id}
    controller: App\Controller\UserController::getUserAction

userUpdate:
    path: user/profile/update/{id}
    controller: App\Controller\UserController::updateUserAction

userDelete:
    path: user/profile/delete/{id}
    controller: App\Controller\UserController::deleteUserAction

#Ajout d'un service par un user
serviceAdd:
    path: user/{id}/addService
    controller: App\Controller\ServiceController::addServiceAction

    

    
# page qui envoi vers tous les services    
serviceGet:
    path: /user/service
    controller: App\Controller\ServiceController::getServiceAction 

servicePage:
  path: /user/service/{id}
  controller: App\Controller\ServiceController::getServicebyIdAction

dashboardUserService:
    path: /user/service/dashboard/{id}
    controller: App\Controller\ServiceController::dashboardServicesAction

serviceMod:
    path: /user/service/update/{id}
    controller: App\Controller\ServiceController::serviceModifyAction

serviceDelete:
  path: /user/service/delete/{id}
  controller: App\Controller\ServiceController::serviceDeleteAction


 
commentaireDelete:
    path: /user/service/deleteComment/{id}
    controller: App\Controller\CommentController::deleteCommentaireAction



getServiceByType:
    path: /user/serviceByType/{id}
    controller: App\Controller\ServiceController::getServiceByType    
 
 

mailbox:
    path: /user/mailbox
    controller: App\Controller\MailboxController::index

mailboxAdd:
    path: /user/mailbox/add
    controller: App\Controller\MailboxController::addMailboxAction
      
mailboxView:
    path: /user/mailbox/view/{id}
    controller: App\Controller\MailboxController::viewMailboxAction
      
mailboxUpdate:
    path: /user/mailbox/update/{id}
    controller: App\Controller\MailboxController::updateMailboxAction
      
mailboxDelete:
    path: /user/mailbox/delete/{id}
    controller: App\Controller\MailboxController::deleteMailboxAction

mailboxOuiDel:
    path: /user/mailbox/ouidel/{id}
    controller: App\Controller\MailboxController::ouidelMailboxAction
    
    
contactAdd:
    path: /contact
    controller: App\Controller\ContactController::addContactAction
      
contactGet:
    path: /admin/contact/{id}
    controller: App\Controller\ContactController::getContactAction
      
contactDelete:
    path: /admin/contact/{id}
    controller: App\Controller\ContactController::deleteContactAction

chooseTypeServices:
    path: /choose/type/{id}
    controller: App\Controller\ChooseTypeServicesController::chooseTypeServicesAction



