#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
    path: /
    controller: App\Controller\PageAccueilController::index

qui_sommes_nous:
    path: /qui-sommes-nous
    controller: App\Controller\QuiSommesNousController::index